### ISSUE TITLE
Cascade breadth should be different from max(in_degree)?

### ISSUE THREAD

**Issue by diogofpacheco** [pnnl/socialsim#14]
My understanding from the code is that the method `cascade_mesurements.get_cascade_breadth` is returning the maximum in-degree in the tree. However, according to _Soroush Vosoughi, Deb Roy, Sinan Aral. The spread of true and false news online. Science. 2018_ this is not the case.

For [example](http://science.sciencemag.org/content/sci/suppl/2018/03/07/359.6380.1146.DC1/aap9559_Vosoughi_SM.pdf), in the figure below, the max in-degree is 3, but the max-breadth is 4:
![image](https://user-images.githubusercontent.com/12305206/46372486-4661be80-c659-11e8-80ff-6634777d2502.png)

**Comment by emily-grace** [comment]
We've updated the implementation of cascade_breadth in the most recent update.  Now, breadth should return as the maximum number of nodes at the same depth.
