### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim#15]
Could you please add and maintain a requirements.txt with all the python libraries required to run this code?

Here are the modules I had to install manually, each added after encountering an exception trying to run the code:

> pandas
> scipy
> sklearn
> statsmodels
> fastdtw
> matplotlib
> pathos
> jpype
> community
> networkx
> tqdm
> pysal
> seaborn

Instead of having to run `pip install` 13 times when encountering a new exception, it would be simpler to just  run `pip install -r requirements.txt` once.

Thanks.

**Comment by j-mend** [comment]
Hello Mouna, 

We will work on getting this released sometime next week. 

Josh M

**Comment by j-mend** [comment]
Hi Mouna, 

We have added two requirements files, one for normal pip and another for anaconda along with environment installation instructions. We also added a link to the one package that needs to be installed manually for the updated network code. 

Josh M

**Comment by mbamba** [comment]
Great, thank you!
