### ISSUE TITLE
load_measurements doesn't handle missing files

### ISSUE THREAD

**Issue by brandon-fsu** [pnnl/socialsim#17]
While utilizing load_measurements, I experienced exceptions when it tries to load a measurement file that is not there. This can happen if a measurement did not compute, but it part of the measurement_params. 

I just wrapped it in a try/except block to get around it

**Comment by emily-grace** [comment]
It looks like there is already a try/except in load_measurements:

https://github.com/pnnl/socialsim/blob/7c396a4889d9d62d197e883e28e51dd833a662b4/december-measurements/run_measurements_and_metrics.py#L404-L408

Does that resolve your issue, or did you need an additional try/except somewhere?

**Comment by brandon-fsu** [comment]
Sorry I wasn't more specific. It has the try/except there, but above there, it tries to open the file and if that file isn't there when it tries to open it, it throws the exception.

**Comment by emily-grace** [comment]
Thanks for the clarification, makes sense.  I've included the file open inside the try block now.
