### ISSUE TITLE
Assertion Error: Seed Nodes

### ISSUE THREAD

**Issue by SamTube405** [pnnl/socialsim#18]
@emily-grace Got several cases where the assertion on seed nodes fails, what does it say?

`def get_depth_of_each_node(self):
....
assert len(set(seed_nodes)) == len(seed_nodes)
...`

**Comment by emily-grace** [comment]
It looks like there are seed nodes (i.e. root tweets or posts) which are present multiple times in the data.  I would check for any duplicates in your data, where you are using the same nodeID multiple times.

Let me know whether or not that seems to be the issue.  If not, I can take a look at your data to reproduce the issue and work on debugging.

**Comment by SamTube405** [comment]
Thanks. Yes, I found duplicate nodeIDs in the ground-truth data.
