### ISSUE TITLE
UserCentricMeasurements.py", line 265 throws TypeError("invalid type comparison")

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim#19]
The following exception is triggered using the attached exerpt of github json event file:

> Measuring ageOfAccounts for simulation data
> socialsim/socialsim/december-measurements/CommunityCentricMeasurements.py:303: UserWarning: Skipping ageOfAccountsHelper because metadata file is required
>   warnings.warn('Skipping ageOfAccountsHelper because metadata file is required')
> Measuring getUserPullRequestAcceptance for simulation data
> miniconda2/lib/python2.7/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
>   result = method(y)
> Traceback (most recent call last):
>   File "run_measurements_and_metrics.py", line 744, in <module>
>     baseline_examples('github')
>   File "run_measurements_and_metrics.py", line 606, in baseline_examples
>     plot_flag=True, output_dir='measurements_output/' + platform + '/')
>   File "run_measurements_and_metrics.py", line 365, in run_all_measurements
>     plot_dir=plot_dir)
>   File "run_measurements_and_metrics.py", line 226, in run_measurement
>     measurement = measurement_function(**measurement_args)
>   File "socialsim/december-measurements/UserCentricMeasurements.py", line 265, in getUserPullRequestAcceptance
>     idx = df['action'] == 'closed'
>   File "miniconda2/lib/python2.7/site-packages/pandas/core/ops.py", line 1283, in wrapper
>     res = na_op(values, other)
>   File "miniconda2/lib/python2.7/site-packages/pandas/core/ops.py", line 1169, in na_op
>     raise TypeError("invalid type comparison")
> TypeError: invalid type comparison

[github_data_sample.json.zip](https://github.com/pnnl/socialsim/files/2511723/github_data_sample.json.zip)

A **print (df['action'])** right before line 265 of UserCentricMeasurements.py reveals:

> Measuring getUserPullRequestAcceptance for simulation data

> 1     NaN
> 82    NaN
> 148   NaN
> 143   NaN
> 156   NaN
> 153   NaN
> 168   NaN
> 182   NaN
> 175   NaN
> 209   NaN
> 226   NaN
> 228   NaN
> 233   NaN
> 258   NaN
> 275   NaN
> 273   NaN
> 267   NaN
> 266   NaN
> 339   NaN
> 347   NaN
> 344   NaN
> 343   NaN
> 362   NaN
> 360   NaN
> 354   NaN
> 376   NaN
> 372   NaN
> 399   NaN
> 411   NaN
> 424   NaN
> 417   NaN
> 426   NaN
> 439   NaN
> 459   NaN
> 457   NaN
> 485   NaN
> 531   NaN
> 643   NaN
> 637   NaN
> 669   NaN
> 711   NaN
> 751   NaN
> 758   NaN
> 814   NaN
> 829   NaN
> 859   NaN
> 883   NaN
> 877   NaN
> 886   NaN
> 913   NaN
> 923   NaN
> 964   NaN
> 966   NaN
> 994   NaN
> 996   NaN
> Name: action, dtype: float64

Is that expected behavior to have all NaN? 

Thanks.

**Comment by mbamba** [comment]
Digging into this, I see from https://wiki.socialsim.info/display/SOC/Simulation+Output+Schema that for github you expect actionSubType ("action") to be set and it is empty in our data so we have to correct this in our files.

It seems you might want to ensure the eval script catches these missing requirements (there might be others than this one) sooner and not crash.

**Comment by emily-grace** [comment]
You're correct, this was because of the blank actionSubType and status fields in the data.  It should work if you leave those fields out rather than setting them as blank strings.

I've also just pushed an update which checks for valid values of those fields for relevant measurements.

**Comment by mbamba** [comment]
Great, thank you for the prompt response!
