### ISSUE TITLE
conflict in conda-requirements

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim#29]
Getting package version conflict using the provided conda-requirements running:

> $conda create --name conda_socialsim --file conda_requirements.txt -c conda-forge python=2.7
Solving environment: failed
> UnsatisfiableError: The following specifications were found to be in conflict:
> - mkl==2019.0=118
> - numpy-base==1.15.2=py27h81de0dd_1 -> mkl[version='>=2018.0.3,<2019.0a0']
> Use "conda info <package>" to see the dependencies for each package.

**Comment by j-mend** [comment]
Hey Mouna, 

I went ahead and updated the requirements file with the one we are using now. We got rid of the mkl dependency. 

Josh M
