### ISSUE TITLE
from somefile import * 

### ISSUE THREAD

**Issue by Jbollenbacher** [pnnl/socialsim#4]
`from somefile import * ` is failing, probably due to not defining the `__all__` variable in the target files.

This bug effects import statements Metrics.py and RepoCentricMeasurements.py.

RepoCentricMeasurements.py, UserCentricMeasurements.py, and plots.py all are missing the `__all__` variable and other files attempt to import them using the wildcard import. 

This bug may depend on the version of python used.  I tested using python 3.5.0, but documentation indicates that all recent versions of python are similarly effected.

**Comment by j-mend** [comment]
Hello, 

Would you mind posting the exact error that is thrown out? 

Best,

Josh M

**Comment by katporter** [comment]
This bug should now be fixed. Python3 does not allow importing within functions. Plots.py was calling an import in one of the methods.

**Comment by Jbollenbacher** [comment]
Here's an example. The same error appears everywhere there is an `import *`, including `from itertools import *` in plots.py line 186


Traceback (most recent call last):
  File "evaluation/Metrics.py", line 11, in <module>
    from RepoCentricMeasurements import *
  File "/gpfs/home/j/m/jmbollen/Karst/github_simulation/evaluation/RepoCentricMeasurements.py", line 6, in <module>
    import plots
  File "/gpfs/home/j/m/jmbollen/Karst/github_simulation/evaluation/plots.py", line 169
    def plot_distribution_of_events(data,weekday,loc=False):
SyntaxError: import * only allowed at module level

**Comment by Jbollenbacher** [comment]
Thanks for the prompt response.
